name: youth_task

on:
  workflow_dispatch:
  schedule:
     - cron: '32 10 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL }}
        YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD }}
        #YOUTH_TASK_URL_SOPHIE: ${{ secrets.YOUTH_TASK_URL_SOPHIE }}
        #YOUTH_TASK_HD_SOPHIE: ${{ secrets.YOUTH_TASK_HD_SOPHIE }} 
        #YOUTH_TASK_URL_WYDSZ: ${{ secrets.YOUTH_TASK_URL_WYDSZ }}
        #YOUTH_TASK_HD_WYDSZ: ${{ secrets.YOUTH_TASK_HD_WYDSZ }}   
        YOUTH_TASK_URL_RL: ${{ secrets.YOUTH_TASK_URL_RL }}
        YOUTH_TASK_HD_RL: ${{ secrets.YOUTH_TASK_HD_RL }}
        YOUTH_TASK_URL_QF: ${{ secrets.YOUTH_TASK_URL_QF }}
        YOUTH_TASK_HD_QF: ${{ secrets.YOUTH_TASK_HD_QF }}  
        #YOUTH_TASK_URL_JH: ${{ secrets.YOUTH_TASK_URL_JH }}
        #YOUTH_TASK_HD_JH: ${{ secrets.YOUTH_TASK_HD_JH }}  
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【youth_task_SamQ】'
        if: env.YOUTH_TASK_HD
        run: |
          node youth/youth_task.js
        env:
          YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL }}
          YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD }}       
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【youth_task_Sophie】'
        if: env.YOUTH_TASK_HD_SOPHIE
        run: |
          node youth/youth_task.js
        env:
          YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL_SOPHIE }}
          YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD_SOPHIE }}       
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【youth_task_WYDSZ】'
        if: env.YOUTH_TASK_HD_WYDSZ
        run: |
          node youth/youth_task.js
        env:
          YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL_WYDSZ }}
          YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD_WYDSZ }}       
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

      - name: '运行 【youth_task_RL】'
        if: env.YOUTH_TASK_HD_RL
        run: |
          node youth/youth_task.js
        env:
          YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL_RL }}
          YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD_RL }}       
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
         
      - name: '运行 【youth_task_QF】'
        if: env.YOUTH_TASK_HD_QF
        run: |
          node youth/youth_task.js
        env:
          YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL_QF }}
          YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD_QF }}       
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【youth_task_JH】'
        if: env.YOUTH_TASK_HD_JH
        run: |
          node youth/youth_task.js
        env:
          YOUTH_TASK_URL: ${{ secrets.YOUTH_TASK_URL_JH }}
          YOUTH_TASK_HD: ${{ secrets.YOUTH_TASK_HD_JH }}       
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}          
